### ISSUE TITLE
搜索功能是对接chatnio吗？

### ISSUE THREAD

**Issue by weikecloud** [Deeptrain-Community/fystart#5]
我搭建了chatnio，发现长链接一直连不上

**Comment by zmh-program** [comment]
只有 AI 智能建议依赖 chatnio，搜索依赖百度搜索，可通过源码查看。

**Comment by zmh-program** [comment]
https://github.com/Deeptrain-Community/fystart/blob/main/src/assets/script/engine.ts#L58-L81

**Comment by weikecloud** [comment]
我看代码也是这样写，我是这样配置的，一直连不上
![image](https://github.com/Deeptrain-Community/fystart/assets/36788191/68ec3af3-defa-4f4e-802a-9864d3e2db24)
![image](https://github.com/Deeptrain-Community/fystart/assets/36788191/4072649c-3f85-4215-b902-aef0847eebb1)

**Comment by zmh-program** [comment]
请提供报错日志

**Comment by weikecloud** [comment]
chatnio没有报错信息，fystart也没报错信息，前端这边显示连不上，是不是chatnio的/chat路由也需要秘钥？

**Comment by zmh-program** [comment]
报错什么，是连不上还是返回错误信息，看浏览器控制台
以及chatnio设置模型不计费并且支持匿名调用就可以不携带密钥请求啊

**Comment by zmh-program** [comment]
首先你本地为何要用wss，是配置ssl证书了么

换成这个试试 `ws://localhost:8000/api` 或者只去掉 s

**Comment by weikecloud** [comment]
原来是这样，配置里面写ws://127.0.0.1:8000/api 就成功了，感谢！

**Comment by weikecloud** [comment]
还有一个就是，里面的登录功能可以自己搭建吗？我看之前有这个仓库的后来没了！

**Comment by zmh-program** [comment]
不能 现在无法自行搭建

**Comment by weikecloud** [comment]
账号管理的功能也只能用你们搭建好的？

**Comment by zmh-program** [comment]
二开。

**Comment by zmh-program** [comment]
如果此issue没有问题，稍后会被关闭。

**Comment by weikecloud** [comment]
好的，感谢！
